# Use a minimal distro as we are going to use docker anyway.
# We could run a Python kafka consumer on this instance so that we can capture the messages sent from OEL7 to the kafka instance
# Python is part of minimal anyway.

language: python

git:
  depth: false # We might not need anything from git at this level?
  
services:
  - docker

env:
  - BUILD_CONFIG=Release

dist: bionic

branches:
  only:
    - master

before_install:
  - echo "Testing Docker Hub credentials"
  
install:
  - export SRC_DIR=$(pwd)
  - mkdir -p build/install && cd build
  - export INSTALL_PREFIX=$(pwd)/install
  - DOCK=$(docker run -d -v $(pwd):/mnt/build --rm -ti library/oraclelinux:7.6)
  - export RUN="docker exec --interactive --workdir /mnt/build $DOCK"
  - export STOP="docker stop $DOCK"
    
script:
  - $RUN ls -lsr
  - $STOP